name: silvertime
description: Silvertime Manager Dashboard.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.3
  dropdown_button2: ^2.0.0
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.4.1
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^7.1.3
  flutter_spinkit: ^5.1.0
  flutter_work_utils: ^0.0.2
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  http_request_utils: ^0.2.8
  intl: ^0.17.0
  intl_utils: ^2.8.2
  jwt_decode: ^0.3.1
  page_transition: ^2.0.9
  provider: ^6.0.5
  searchfield: ^0.7.5
  shared_preferences: ^2.0.20
  skeletons: ^0.0.3
  url_strategy: ^0.2.0

dependency_overrides:
  collection: ^1.16.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: false
  image_path: "assets/logos/logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logos/

flutter_intl:
  enabled: true
